name: CI

on:
  workflow_dispatch:
 
jobs:
  print-env:
    runs-on: ubuntu-latest
    environment: dev
    env:
      DUMMY: ${{ secrets.DUMMY }}
    steps:
      - name: print
        run: |
          printenv
